name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Log in to Heroku
      run: heroku container:login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Build Docker Image
      run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web ./user_interface

    - name: Push to Heroku
      run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Release Heroku App
      run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}