name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Build the Docker image
    - name: Build Docker Image
      run: docker build -t proyectosoftarchitecture-api .

    # Tag the image for Heroku
    - name: Tag Image for Heroku
      run: docker tag proyectosoftarchitecture-api:latest registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    # Push the image to Heroku
    - name: Push to Heroku
      run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    # Release the image on Heroku
    - name: Release Heroku App
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}

